Milestone 2 - BookStore React
kazumaki/redux-bookstore pull request #2
Opened 2020-06-03 15:57 UTC by fivan18

## Specific requirements
- [ ] Prepare the directory structure
- [ ] Implement the App component
- [ ] Implement the BooksList component
- [ ] Implement the Book component
- [ ] Implement the BooksForm component
- [ ] Define the Redux actions and reducers
- [ ] Initialize the Redux store

2020-06-04 10:08 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**1.`src/reducers/index.js` should combine all our reducers, but for now, we have only `book.js` reducer;
checkout [Combine Reducer](https://redux.js.org/recipes/structuring-reducers/using-combinereducers)**
screenshot below;
![image](https://user-images.githubusercontent.com/31897434/83742970-f8813300-a651-11ea-833f-a68af14d9a09.png)

**2. Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-04 10:08 UTC, bellom commented on src/components/BooksForm.js
> +import React from 'react';
Good job so far!

we should keep `bookForm` inside a container folder
screenshot from pathwright below;
![image](https://user-images.githubusercontent.com/31897434/83742194-0aaea180-a651-11ea-934f-21f0fc6960e8.png)

2020-06-04 10:08 UTC, bellom commented on src/components/BooksList.js
> +import React from 'react';
Good job so far!

we should keep `bookList` inside a container folder
screenshot from pathwright below;
![image](https://user-images.githubusercontent.com/31897434/83742194-0aaea180-a651-11ea-934f-21f0fc6960e8.png)

2020-06-04 10:08 UTC, bellom commented on src/reducers/books.js
> +];
According to the pathwright, you are supposed to create the book object inside `src/index.js`.
screenshot below;
![image](https://user-images.githubusercontent.com/31897434/83743295-70e7f400-a652-11ea-8474-506494691d91.png)

2020-06-05 13:21 UTC, AdnanAfsari approved these changes
**Status: Approved**

Hello @fivan18 @kazumaki ✋ 

Well done 👏 . It's a 👍  from me.

Happy Coding
Adnan Afsari

2020-06-05 14:27 UTC, merged